# Generated by Django 4.0.5 on 2022-06-13 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=10, unique=True)),
                ('effective_date', models.DateTimeField(default=datetime.datetime.now)),
                ('previous_policy_cancelled', models.BooleanField(default=False)),
                ('owns_property_to_be_insured', models.BooleanField(default=False)),
            ],
        ),
    ]
