# Generated by Django 4.0.5 on 2022-06-14 00:51

import datetime
from django.db import migrations, models
import rest_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        default=rest_api.models.get_random_quote_string,
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(default=datetime.date(2022, 6, 14)),
                ),
                ("previous_policy_cancelled", models.BooleanField(default=False)),
                ("owns_property_to_be_insured", models.BooleanField(default=False)),
                ("property_zip_code", models.CharField(max_length=50)),
                ("property_state", models.CharField(max_length=50)),
            ],
        ),
    ]
