# Generated by Django 4.0.5 on 2022-06-14 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="effective_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
