# Generated by Django 4.0.5 on 2022-06-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0002_alter_quote_effective_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="owns_property_to_be_insured",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="quote",
            name="previous_policy_cancelled",
            field=models.BooleanField(),
        ),
    ]
